{
 "title": "API-Gateway System overview",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Service-Name",
    "query": {
     "query": "label_values(axway_api_requests_total, service)"
    }
   },
   {
    "name": "gatewayId",
    "label": "Gateway-Id",
    "query": {
     "query": "label_values(axway_apigateway_version_info, gatewayId)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "API-Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(axway_api_requests_total{gatewayId=~\"$gatewayId\", service=~\"$service\" }[5m]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(axway_api_requests_exceptions{}[5m]))",
     "legendFormat": "Exceptions"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "axway_apigateway_system_memory_total_bytes{gatewayId=~\"$gatewayId\"}",
     "legendFormat": "Mem Max {{gatewayId}}"
    },
    {
     "expr": "axway_apigateway_system_memory_used_bytes{gatewayId=~\"$gatewayId\"}",
     "legendFormat": "Mem System {{gatewayId}}"
    },
    {
     "expr": "axway_apigateway_memory_used_bytes{gatewayId=~\"$gatewayId\"}",
     "legendFormat": "Mem Gateway {{gatewayId}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "axway_apigateway_system_cpu_ratio{gatewayId=~\"$gatewayId\"}",
     "legendFormat": "System CPU {{gatewayId}}"
    },
    {
     "expr": "axway_apigateway_instance_cpu_ratio{gatewayId=~\"$gatewayId\"}",
     "legendFormat": "Gateway CPU {{gatewayId}}"
    }
   ]
  },
  {
   "title": "API request last 10 minutes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(axway_api_requests_success[10m]))",
     "legendFormat": "Successes last 10 Minutes"
    },
    {
     "expr": "sum(increase(axway_api_requests_failures[10m]))",
     "legendFormat": "Failures last 10 Minutes"
    },
    {
     "expr": "sum(increase(axway_api_requests_exceptions[10m]))",
     "legendFormat": "Failures last 10 Minutes"
    }
   ]
  },
  {
   "title": "Gateway disk usage",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "axway_apigateway_instance_disk_used_ratio{gatewayId=~\"$gatewayId\"}",
     "legendFormat": "{{gatewayId}}"
    }
   ]
  },
  {
   "title": "API Request duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(increase(axway_api_requests_duration_milliseconds_bucket{gatewayId=~\"$gatewayId\", service=~\"$service\"}[5m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}