swagger: '2.0'
info:
  title: Prometheus-Metrics
  version: '1.0'
host: 'localhost:3000'
schemes:
  - http
produces:
  - application/json
consumes:
  - application/json
paths:
  /metrics:
    get:
      summary: Returns metrics collected from ANM
      tags: []
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties: {}
      operationId: get-metrics
      description: Returns metrics collected from Admin-Node-Manager
      x-flow: Prometheus-Metrics-get-metrics
  /collect/metrics/service:
    get:
      summary: Collect Service metrics manually
      tags: []
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties: {}
      operationId: get-collect-metrics-service
      description: >-
        This endpoint can be used to manually trigger the collect and
        Prom-Registry update process for Services
      x-flow: Prometheus-Metrics-get-collect-metrics-service
definitions:
  User:
    title: User
    type: object
    properties:
      id:
        type: integer
        description: Unique identifier for the given user.
      firstName:
        type: string
      lastName:
        type: string
      email:
        type: string
        format: email
      dateOfBirth:
        type: string
        format: date
        example: '1997-10-31'
      emailVerified:
        type: boolean
        description: Set to true if the user's email has been verified.
      createDate:
        type: string
        format: date
        description: The date that the user was created.
    required:
      - id
      - firstName
      - lastName
      - email
      - emailVerified
