apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "axway-apim-prometheus.fullname" . }}
  labels:
    {{- include "axway-apim-prometheus.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "axway-apim-prometheus.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "axway-apim-prometheus.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "axway-apim-prometheus.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.global.repository }}/{{ .Values.global.image }}:{{ .Values.global.imageTag }}"
          imagePullPolicy: {{ .Values.global.pullPolicy }}
          ports:
            - name: http
              containerPort: 8443
              protocol: TCP
          env: 
          - name: ANM_URL
            value: {{ required "Missing .Values.anm.url" .Values.anm.url | quote }}
          - name: ANM_USERNAME
            value: {{ required "Missing .Values.anm.username" .Values.anm.username | quote }}
          - name: ANM_PASSWORD
            value: {{ required "Missing .Values.anm.password" .Values.anm.password | quote }}
          - name: LOG_LEVEL
            value: "debug"
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
