apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "axway-apim-prometheus.fullname" . }}
  labels:
    {{- include "axway-apim-prometheus.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "axway-apim-prometheus.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "axway-apim-prometheus.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "axway-apim-prometheus.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.global.repository }}/{{ .Values.global.image }}:{{ default .Chart.AppVersion .Values.global.imageTag }}"
          imagePullPolicy: {{ .Values.global.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env: 
          - name: ANM_URL
            value: {{ required "Missing .Values.config.anm.url" .Values.config.anm.url | quote }}
          - name: ANM_USERNAME
            value: {{ required "Missing .Values.config.anm.username" .Values.config.anm.username | quote }}
          - name: ANM_PASSWORD
        {{- if .Values.config.anm.existingSecret }}
            valueFrom:
              secretKeyRef:
                name: {{ .Values.config.anm.existingSecret | quote }}
                key: {{ .Values.config.anm.existingSecretPasswordKey | quote }}
        {{- else }}
            value: {{ required "Missing .Values.config.anm.password or an existingSecret" .Values.config.anm.password | quote }}
        {{- end }}
          - name: LOG_LEVEL
            value: {{ default "info" .Values.config.logLevel | quote }}
          - name: POLL_SERVICE_METRICS_INTERVAL
            value: {{ default "15000" .Values.config.pollServiceMetricsInterval | quote }}
          - name: POLL_SYSTEM_METRICS_INTERVAL
            value: {{ default "15000" .Values.config.pollSystemMetricsInterval | quote }}
            
          livenessProbe:
            httpGet:
              path: /api/metrics
              port: http
          readinessProbe:
            httpGet:
              path: /api/metrics
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
