{{- if .Values.ingress.enabled -}}
{{- if .Capabilities.APIVersions.Has "route.openshift.io/v1/Route" }}
{{- $fullName := include "axway-apim-prometheus.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ $fullName }}
spec:
  to:
    kind: Service
    name: {{ $fullName }}
  port:
    targetPort: {{ $svcPort }}
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
{{- end }}
{{- end }}