flow-nodes:
  prometheus-metrics:
    name: Prometheus metrics
    icon: prom-icon.png
    description: Flow node used to generate required Prometheus metrics
    category: Prometheus
    methods:
      processTopologyInfo: 
        name: Process topology information
        description: Extracts version information from the topology to update the internal metrics registry.
        parameters:
          gatewayTopology:
            name: Gateway topology
            description: Gateway topology information.
            required: true
            schema:
              type: object
        returns:
          name: Next
          description: The SystemOverview Metrics-Registry
          context: $.systemOverviewMetricsRegistry
          schema:
            type: object
        throws:
          name: Error
          description: An unexpected error was encountered.
          context: $.error
          schema:
            type: object
            properties:
              message:
                type: string
      processSummaryMetrics: 
        name: Process summary metrics
        description: Processes the given summary metrics. Currently it is used to extract system overview information to update the System Prometheus-Metrics registry.
        parameters:
          summaryMetrics:
            name: Summary metrics
            description: Array of summary metrics
            required: true
            schema:
              type: array
        returns:
          name: Next
          description: The SystemOverview Metrics-Registry
          context: $.systemOverviewMetricsRegistry
          schema:
            type: object
        throws:
          name: Error
          description: An unexpected error was encountered.
          context: $.error
          schema:
            type: object
            properties:
              message:
                type: string

      processServiceMetricsFromSystemOverview: 
        name: Service metrics from SystemOverview
        description: Gets the Service information summary from SystemOverview due to https://support.axway.com/en/case-global/view/id/01314580
        parameters:
          systemOverviewMetrics:
            name: System overview metrics
            description: System overview metrics collected from the ANM.
            required: true
            schema:
              type: array
        returns:
          name: Next
          description: The Service Metrics-Registry
          context: $.serviceMetricsRegistry
          schema:
            type: object
        throws:
          name: Error
          description: An unexpected error was encountered.
          context: $.error
          schema:
            type: object
            properties:
              message:
                type: string

      processServiceMetrics: 
        name: Process Service metrics
        description: Processes the given Service metrics and updates the Service-Registry metrics.
        parameters:
          serviceMetrics:
            name: Service metrics
            description: Service metrics collected from the ANM.
            required: true
            schema:
              type: array
        returns:
          name: Next
          description: The Service Metrics-Registry
          context: $.serviceMetricsRegistry
          schema:
            type: object
        throws:
          name: Error
          description: An unexpected error was encountered.
          context: $.error
          schema:
            type: object
            properties:
              message:
                type: string

      getMetrics: 
        name: Get metrics
        description: Get the metrics based on the current state of the internal metrics registry
        parameters:
          returnMetrics:
            name: Return metrics
            description: If true, the flow returns the metrics as required by the Prometheus scraper.
            required: false
            initialType: boolean
            schema:
              default: false
              type: boolean
        returns:
          name: Next
          description: The SystemOverview Metrics-Registry
          context: $.metrics
          schema:
            oneOf:
              - type: string
              - type: object
        throws:
          name: Error
          description: An unexpected error was encountered.
          context: $.error
          schema:
            type: object
            properties:
              message:
                type: string