flow-nodes:
  prometheus-metrics:
    name: Prometheus metrics
    icon: prom-icon.png
    description: Flow node used to generate required Prometheus metrics
    category: Prometheus
    methods:
      processTopologyInfo: 
        name: Process topology information
        description: Extracts version information from the topology to update the internal metrics registry.
        parameters:
          gatewayTopology:
            name: Gateway topology
            description: Gateway topology information.
            required: true
            schema:
              type: object
        returns:
          name: Next
          description: The SystemOverview Metrics-Registry
          context: $.systemOverviewMetricsRegistry
          schema:
            type: object
        throws:
          name: Error
          description: An unexpected error was encountered.
          context: $.error
          schema:
            type: object
            properties:
              message:
                type: string

      processSystemMetrics: 
        name: Process system metrics
        description: Processes the given system metrics.
        parameters:
          systemMetrics:
            name: System metrics
            description: Array of system metrics for each API-Gateway instance
            required: true
            schema:
              type: array
        returns:
          name: Next
          description: The System Metrics-Registry
          context: $.systemOverviewMetricsRegistry
          schema:
            type: object
        throws:
          name: Error
          description: An unexpected error was encountered.
          context: $.error
          schema:
            type: object
            properties:
              message:
                type: string

      processServiceMetrics: 
        name: Process Service metrics
        description: Processes the given Service metrics and updates the Service-Registry metrics.
        parameters:
          serviceMetrics:
            name: Service metrics
            description: Service metrics collected from the ANM.
            required: true
            schema:
              type: array
        returns:
          name: Next
          description: The Service Metrics-Registry
          context: $.serviceMetricsRegistry
          schema:
            type: object
        throws:
          name: Error
          description: An unexpected error was encountered.
          context: $.error
          schema:
            type: object
            properties:
              message:
                type: string

      getMetrics: 
        name: Get metrics
        description: Get the metrics based on the current state of the internal metrics registry
        parameters:
          returnMetrics:
            name: Return metrics
            description: If true, the flow returns the metrics as required by the Prometheus scraper.
            required: false
            initialType: boolean
            schema:
              default: false
              type: boolean
        returns:
          name: Next
          description: The SystemOverview Metrics-Registry
          context: $.metrics
          schema:
            oneOf:
              - type: string
              - type: object
        throws:
          name: Error
          description: An unexpected error was encountered.
          context: $.error
          schema:
            type: object
            properties:
              message:
                type: string